#!/bin/sh

kexec --load /boot/vmlinuz-linux-lts --initrd=/boot/initramfs-linux-lts.img --append="root=LABEL=DOROOT init=/usr/lib/systemd/systemd" && mount -o ro,remount / && kexec -e

exec /usr/lib/systemd/systemd

